version: '2'
services:
    testk8s-app:
        image: testk8s
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testk8s-postgresql:5432/testk8s
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testk8s-postgresql:
        extends:
            file: postgresql.yml
            service: testk8s-postgresql
